config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,
           path: "customers",
           controllers: { sessions: "customers/authentication/sessions" }

  unauthenticated do
    root "landing_pages#show"
  end

  authenticated :customer do
    root "customers/homes#show", as: :customer_root
  end

  resource :landing_page, only: [:show]

  resources :customers, only: [], module: :customers do
    resources :bookmarks, only: [:index]
    resource :homes, only: [:show]
    resources :movies, only: [:index]
    resources :tvs, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_one_attached :avatar
end

app/models/show.rb
class Show < ApplicationRecord
  enum :category, { tv_series: 0, movie: 1 }, prefix: true
  enum :rating, { e: 0, u: 1, pg: 2, "18": 3 }, prefix: true

  has_one_attached :regular_image do |attachable|
    attachable.variant :large, resize_to_limit: [560, 348]
    attachable.variant :medium, resize_to_limit: [440, 280]
    attachable.variant :small, resize_to_limit: [323, 220]
  end

  has_one_attached :trending_image do |attachable|
    attachable.variant :large, resize_to_limit: [940, 460]
    attachable.variant :small, resize_to_limit: [480, 280]
  end

  validates :category,
            :rating,
            :title,
            :year,
            presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  enum role: { customer: 0, staff: 1 }, _suffix: true

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers/Authentication/sessions_controller.rb
# frozen_string_literal: true

module Customers
  module Authentication
    class SessionsController < Devise::SessionsController
      # GET /resource/sign_in
      def new
        super do |_|
          @customers = Customer.all.limit(5)
        end
      end
    end
  end
end

app/controllers/customers/base_controller.rb
module Customers
  class BaseController < ApplicationController
    before_action :authenticate_customer!
    layout "customer"
  end
end

app/controllers/customers/bookmarks_controller.rb
module Customers
  class BookmarksController < BaseController
    def index
      @bookmarked_movies = Show.where(category: "movie").limit(5)
      @bookmarked_tv_shows = Show.where(category: "tv_series").limit(5)
    end
  end
end

app/controllers/customers/homes_controller.rb
module Customers
  class HomesController < Customers::BaseController
    def show
      @trending = Show.where(trending: true)
      @shows = Show.all
    end
  end
end

app/controllers/customers/movies_controller.rb
module Customers
  class MoviesController < BaseController
    def index
      @movies = Show
                .with_attached_regular_image
                .where(category: "movie")
    end
  end
end

app/controllers/customers/tvs_controller.rb
module Customers
  class TvsController < BaseController
    def index
      @tv_series = Show.where(category: "tv_series")
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show]
  before_action :authorized?, only: %i[show]

  def show; end

  private

  def set_customer
    @customer = User.find(params[:id])
  end

  def authorized?
    return if Customers::CustomersShowPolicy.new(current_user, @customer).show?

    head :unauthorized
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def show; end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def show; end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def new
      super do |_|
        @users = User.all.limit(5)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enum_helper.rb
module EnumHelper
  def human_enum_name(model_name:, enum_name:, enum_key:)
    I18n.t("activerecord.attributes.#{model_name}.#{enum_name.to_s.pluralize}.#{enum_key}")
  end
end

app/helpers/svg_helper.rb
module SVGHelper
  def show_svg(path)
    File.open("app/assets/images/#{path}", "rb") do |file|
      file.read.html_safe
    end
  end
end

app/views/customers/bookmarks/index.html.erb
<div class="mt-6 sm:mt-7 lg:mt-16">
  <%= render(SearchComponent.new(placeholder: "Search for bookmarked shows")) %>
</div>

<section id="bookmarked-movies" class="mx-4 text-skin-background-text">
  <h2 class="text-skin-background-text">Bookmarked Movies</h2>

  <div id="articles" class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-x-7 sm:gap-y-8 lg:gap-x-10">
    <% @bookmarked_movies.each do |show| %>
      <article class="">
        <h3><%= show.title %></h3>
        <%= show.year %>
        <%= show.category %>
        <%= show.rating %>
        <%= show.bookmarked %>
        <%= show.trending %>
      </article>
    <% end %>
  </div>
</section>

<section id="bookmarked-tv-series" class="mx-4 mt-6 sm:mt-10 text-skin-background-text">
  <h2 class="text-skin-background-text">Bookmarked TV Series</h2>

  <div id="articles" class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-x-7 sm:gap-y-8 lg:gap-x-10">
    <% @bookmarked_tv_shows.each do |show| %>
      <article class="">
        <h3><%= show.title %></h3>
        <%= show.year %>
        <%= show.category %>
        <%= show.rating %>
        <%= show.bookmarked %>
        <%= show.trending %>
      </article>
    <% end %>
  </div>
</section>

app/views/customers/homes/show.html.erb
<div class="mt-6 sm:mt-7">
  <%= render(SearchComponent.new(placeholder: "Search for movies or TV series")) %>
</div>

<section id="trending" class="mx-4 text-skin-background-text">
  <h2 class="mt-6 text-skin-background-text">Trending</h2>

  <div id="articles" class="flex">
    <% @trending.each do |show| %>
      <article class="">
        <h3><%= show.title %></h3>
        <%= show.year %>
        <%= show.category %>
        <%= show.rating %>
        <%= show.bookmarked %>
        <%= show.trending %>
      </article>
    <% end %>
  </div>
</section>

<section id="recommended" class="mx-4 mt-6 sm:mt-10 text-skin-background-text">
  <h2 class="text-skin-background-text">Recommended for you</h2>

  <div id="articles" class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-x-7 sm:gap-y-8 lg:gap-x-10">
    <% @shows.each do |show| %>
      <article class="">
        <h3><%= show.title %></h3>
        <%= show.year %>
        <%= show.category %>
        <%= show.rating %>
        <%= show.bookmarked %>
        <%= show.trending %>
      </article>
    <% end %>
  </div>
</section>

app/views/customers/movies/index.html.erb
<div class="mt-6 sm:mt-7 lg:mt-16">
  <%= render(SearchComponent.new(placeholder: "Search for movies")) %>
</div>

<section class="mx-4 text-skin-background-text">
  <h2 class="text-skin-background-text">Movies</h2>

  <div id="articles" class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-x-7 sm:gap-y-8 lg:gap-x-10">
   <%= render(ShowComponent.with_collection(@movies)) %>
  </div>
</section>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_customer_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <span class="body-md text-skin-surface-text">Don't have an account?</span>
  <%= link_to "Sign up", new_customer_registration_path, class: "ml-2.5 body-md text-skin-primary" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/customers/tvs/index.html.erb
<div class="mt-6 sm:mt-7 lg:mt-16">
  <%= render(SearchComponent.new(placeholder: "Search for TV series")) %>
</div>

<section class="mx-4 text-skin-background-text">
  <h2 class="text-skin-background-text">TV Series</h2>

  <div id="articles" class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-x-7 sm:gap-y-8 lg:gap-x-10">
    <% @tv_series.each do |tv_series| %>
      <article class="">
        <h3><%= tv_series.title %></h3>
        <%= tv_series.year %>
        <%= tv_series.category %>
        <%= tv_series.rating %>
        <%= tv_series.bookmarked %>
        <%= tv_series.trending %>
      </article>
    <% end %>
  </div>
</section>

app/views/landing_pages/show.html.erb
<navbar class="flex items-center justify-between pt-4 px-10">
  <h1 class="text-3xl text-skin-background-text">Entertainment</h1>
  <div class="bg-skin-primary text-skin-primary-text">
  </div>
  <%= link_to new_customer_session_path, class:"inline-flex items-center px-6 py-4 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm bg-skin-primary text-skin-primary-text hover:bg-skin-primary-hover hover:text-skin-primary-text-hover focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
    Sign In
  <% end %>
</navbar>

<div class="flex flex-col items-center px-10">
  <div class="pt-6">
    <%= show_svg "logo.svg" %>
  </div>
  <div class="py-6">
    <%= image_tag "image-landing-splash.jpg" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntertainmentWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;500&display=swap" rel="stylesheet">
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body class="bg-skin-background font-sans">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/customer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntertainmentWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;500&display=swap" rel="stylesheet">
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body class="bg-skin-background font-sans">
    <p class="notice text-skin-background-text"><%= notice %></p>
    <p class="alert text-skin-background-text"><%= alert %></p>
    <div class="lg:grid lg:grid-cols-[128px_1fr] lg:h-screen lg:max-h-[960px]">
      <div class="justify-self-end lg:w-24">
        <%= render(NavigationComponent.new(current_customer: current_customer)) %>
      </div>
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/staffs/show.html.erb
<div class="text-skin-background-text">staff show</div>
<h2 class="text-skin-background-text">All Shows</h2>